// This file is auto-generated by @analogjs/platform
// Do not edit manually

declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/getting-started': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/guides/publishing': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/packages/docs-angular': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/packages/markdown-pipeline': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/[[...slug]]': {
      params: { slug?: string[] };
      paramsOutput: { slug?: string[] };
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
  }
}

export {};

export interface AnalogGeneratedRouteRecord<
  TId extends string = string,
  TPath extends string = string,
  TFullPath extends string = string,
  TParentId extends string | null = string | null,
  TChildren extends readonly string[] = readonly string[],
> {
  id: TId;
  path: TPath;
  fullPath: TFullPath;
  parentId: TParentId;
  children: TChildren;
  sourceFile: string;
  kind: 'page' | 'content';
  hasParamsSchema: boolean;
  hasQuerySchema: boolean;
  hasJsonLd: boolean;
  isIndex: boolean;
  isGroup: boolean;
  isCatchAll: boolean;
  isOptionalCatchAll: boolean;
}

export interface AnalogFileRoutesById {
  "/index": AnalogGeneratedRouteRecord<"/index", "/", "/", null, readonly []>;
  "/docs": AnalogGeneratedRouteRecord<"/docs", "docs", "/docs", null, readonly ["/docs/getting-started", "/docs/guides/publishing", "/docs/packages/docs-angular/index", "/docs/packages/markdown-pipeline/index", "/docs/[[...slug]]"]>;
  "/docs/getting-started": AnalogGeneratedRouteRecord<"/docs/getting-started", "getting-started", "/docs/getting-started", "/docs", readonly []>;
  "/docs/guides/publishing": AnalogGeneratedRouteRecord<"/docs/guides/publishing", "guides/publishing", "/docs/guides/publishing", "/docs", readonly []>;
  "/docs/packages/docs-angular/index": AnalogGeneratedRouteRecord<"/docs/packages/docs-angular/index", "packages/docs-angular", "/docs/packages/docs-angular", "/docs", readonly []>;
  "/docs/packages/markdown-pipeline/index": AnalogGeneratedRouteRecord<"/docs/packages/markdown-pipeline/index", "packages/markdown-pipeline", "/docs/packages/markdown-pipeline", "/docs", readonly []>;
  "/docs/[[...slug]]": AnalogGeneratedRouteRecord<"/docs/[[...slug]]", "[[...slug]]", "/docs/[[...slug]]", "/docs", readonly []>;
}

export interface AnalogFileRoutesByFullPath {
  "/": AnalogFileRoutesById["/index"];
  "/docs": AnalogFileRoutesById["/docs"];
  "/docs/getting-started": AnalogFileRoutesById["/docs/getting-started"];
  "/docs/guides/publishing": AnalogFileRoutesById["/docs/guides/publishing"];
  "/docs/packages/docs-angular": AnalogFileRoutesById["/docs/packages/docs-angular/index"];
  "/docs/packages/markdown-pipeline": AnalogFileRoutesById["/docs/packages/markdown-pipeline/index"];
  "/docs/[[...slug]]": AnalogFileRoutesById["/docs/[[...slug]]"];
}

export type AnalogRouteTreeId = keyof AnalogFileRoutesById;
export type AnalogRouteTreeFullPath = keyof AnalogFileRoutesByFullPath;

export const analogRouteTree = {
  byId: {
    "/index": {
      id: "/index",
      path: "/",
      fullPath: "/",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/index.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/index"],
    "/docs": {
      id: "/docs",
      path: "docs",
      fullPath: "/docs",
      parentId: null,
      children: ["/docs/getting-started", "/docs/guides/publishing", "/docs/packages/docs-angular/index", "/docs/packages/markdown-pipeline/index", "/docs/[[...slug]]"] as const,
      sourceFile: "/src/app/pages/docs.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs"],
    "/docs/getting-started": {
      id: "/docs/getting-started",
      path: "getting-started",
      fullPath: "/docs/getting-started",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/getting-started.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/getting-started"],
    "/docs/guides/publishing": {
      id: "/docs/guides/publishing",
      path: "guides/publishing",
      fullPath: "/docs/guides/publishing",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/guides/publishing.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/guides/publishing"],
    "/docs/packages/docs-angular/index": {
      id: "/docs/packages/docs-angular/index",
      path: "packages/docs-angular",
      fullPath: "/docs/packages/docs-angular",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/packages/docs-angular/index.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/packages/docs-angular/index"],
    "/docs/packages/markdown-pipeline/index": {
      id: "/docs/packages/markdown-pipeline/index",
      path: "packages/markdown-pipeline",
      fullPath: "/docs/packages/markdown-pipeline",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/packages/markdown-pipeline/index.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/packages/markdown-pipeline/index"],
    "/docs/[[...slug]]": {
      id: "/docs/[[...slug]]",
      path: "[[...slug]]",
      fullPath: "/docs/[[...slug]]",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/app/pages/docs/[[...slug]].page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: true,
    } satisfies AnalogFileRoutesById["/docs/[[...slug]]"],
  },
  byFullPath: {
    "/": "/index",
    "/docs": "/docs",
    "/docs/getting-started": "/docs/getting-started",
    "/docs/guides/publishing": "/docs/guides/publishing",
    "/docs/packages/docs-angular": "/docs/packages/docs-angular/index",
    "/docs/packages/markdown-pipeline": "/docs/packages/markdown-pipeline/index",
    "/docs/[[...slug]]": "/docs/[[...slug]]",
  },
} as const;
